apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 80;
      index indes.php index.html;
      root /usr/share/nginx/html;

      rewrite ^/google$ https://google.com permanent;
    }